Vagrant.configure("2") do |config|
    config.vm.box = "geerlingguy/ubuntu2004"
    config.vm.hostname = "jenkins"
    config.vm.network "private_network", ip: "192.168.56.130"
    config.vm.provision "shell", path: "install-jenkins.sh"
  end