pipeline {
  agent any
  environment {
    JAVA_HOME = '/usr/lib/jvm/java-8-openjdk-amd64/jre'
  }
  stages {
    stage ('Build') {
      steps {
        sh './gradlew build --no-daemon'
        archiveArtifacts artifacts: 'dist/artifact.zip'
      }
    }
  }
}